DATA SEGMENT
  NUMBER DW 1210h
  NUMB2 DW  9D4Bh
  NUMB1 DD 5A829D4Bh
  STRIN DB 'SOMETHING'
DATA ENDS

INITDS MACRO NUMBER
  INC NUMBER
  ENDM

CODE1 SEGMENT 
  INITDS AX
  TEST_START:
  SCASB
  NUMB3 DD 5A829D4Bh
  CMP BX, AX
  JB WORKPLACE
  DEC NUMB2
  DEC WORD PTR [BX]
  WORKPLACE:
  AND NUMBER, BX
  OR CX, NUMB2
  MOV AX,[SI]
  INC AX
  INITDS BX
  INITDS BL
  INITDS CL
  DEC NUMBER
  MOV AX, 0Bh
  ADD NUMB2, 0Bh
  MOV CX, DS:[DI]
  MOV DX, ES:[BX]
  JB TEST_START
  CODE1 ENDS
END
